// ============================================
// translate.js - ترجمة شاملة وآمنة
// لا يكسر أي شي - يحفظ النص الأصلي لكل عنصر
// ============================================
(function(){
var dict = {
'الصفحات العامة':{en:'Public Pages',no:'Offentlige sider'},
'الرئيسية':{en:'Home',no:'Hjem'},
'النظام الداخلي':{en:'Bylaws',no:'Vedtekter'},
'التصويت':{en:'Voting',no:'Avstemning'},
'الأخبار':{en:'News',no:'Nyheter'},
'المحاسبة':{en:'Finance',no:'Økonomi'},
'خارطة المنتسبين':{en:'Members Map',no:'Medlemskart'},
'استمارة الانتساب':{en:'Registration',no:'Registrering'},
'محرر الدعوات':{en:'Invitation Editor',no:'Invitasjonsredigerer'},
'دعوة المؤتمر':{en:'Conference Invitation',no:'Konferanseinvitasjon'},
'التقارير والإحصائيات':{en:'Reports & Statistics',no:'Rapporter og statistikk'},
'تواصل معنا':{en:'Contact Us',no:'Kontakt oss'},
'معرض الصور':{en:'Photo Gallery',no:'Bildegalleri'},
'البث المباشر':{en:'Live Stream',no:'Direktesending'},
'لوحة الإدارة':{en:'Admin Panel',no:'Administrasjon'},
'الإعدادات':{en:'Settings',no:'Innstillinger'},
'إدارة الأعضاء':{en:'Manage Members',no:'Administrer medlemmer'},
'طلبات الانتساب':{en:'Membership Requests',no:'Medlemsforespørsler'},
'استمارة التسجيل':{en:'Registration Sheet',no:'Registreringsskjema'},
'إدارة المعاملات':{en:'Manage Transactions',no:'Administrer transaksjoner'},
'إدارة الأخبار':{en:'Manage News',no:'Administrer nyheter'},
'إدارة التصويت':{en:'Manage Voting',no:'Administrer avstemning'},
'إدارة البث المباشر':{en:'Manage Live Stream',no:'Administrer direktesending'},
'إدارة معرض الصور':{en:'Manage Gallery',no:'Administrer galleri'},
'دخول المسؤول':{en:'Admin Login',no:'Admin innlogging'},
'خروج':{en:'Logout',no:'Logg ut'},
'الزوار':{en:'Visitors',no:'Besøkende'},
'مرحباً بكم في الجالية الفلسطينية':{en:'Welcome to the Palestinian Community',no:'Velkommen til det palestinske samfunnet'},
'مرحباً بكم':{en:'Welcome',no:'Velkommen'},
'نجمع شملنا في روغالاند - النرويج':{en:'Uniting in Rogaland - Norway',no:'Vi samles i Rogaland - Norge'},
'انضم إلينا':{en:'Join Us',no:'Bli med'},
'الوصول السريع':{en:'Quick Access',no:'Hurtigtilgang'},
'عضو':{en:'Member',no:'Medlem'},
'عائلة':{en:'Family',no:'Familie'},
'خبر':{en:'News',no:'Nyhet'},
'تصويت نشط':{en:'Active Vote',no:'Aktiv avstemning'},
'آخر الأخبار':{en:'Latest News',no:'Siste nyheter'},
'عرض الكل ←':{en:'View All ←',no:'Vis alle ←'},
'عن الجالية':{en:'About Us',no:'Om oss'},
'رؤيتنا':{en:'Our Vision',no:'Vår visjon'},
'رسالتنا':{en:'Our Mission',no:'Vårt oppdrag'},
'جالية فلسطينية متماسكة ومؤثرة':{en:'A cohesive and influential Palestinian community',no:'Et sammensveiset og innflytelsesrikt palestinsk samfunn'},
'خدمة أبناء الجالية والحفاظ على الهوية':{en:'Serving community members and preserving identity',no:'Tjene samfunnsmedlemmer og bevare identiteten'},
'الفعاليات القادمة':{en:'Upcoming Events',no:'Kommende arrangementer'},
'تابعونا':{en:'Follow Us',no:'Følg oss'},
'فيسبوك':{en:'Facebook',no:'Facebook'},
'انستغرام':{en:'Instagram',no:'Instagram'},
'واتساب':{en:'WhatsApp',no:'WhatsApp'},
'البريد':{en:'Email',no:'E-post'},
'نحن مجموعة من أبناء فلسطين في روغالاند - النرويج، نسعى للحفاظ على هويتنا وتراثنا الفلسطيني وتقوية الروابط بين أبناء الجالية.':{en:'We are a group of Palestinians in Rogaland - Norway, working to preserve our identity, heritage, and strengthen community bonds.',no:'Vi er en gruppe palestinere i Rogaland - Norge, som jobber for å bevare vår identitet, kulturarv og styrke fellesskapsbåndene.'},
'لا توجد فعاليات قادمة':{en:'No upcoming events',no:'Ingen kommende arrangementer'},
'شارك في التصويت الآن':{en:'Vote now',no:'Stem nå'},
'شارك في التصويت ←':{en:'Participate in voting ←',no:'Delta i avstemningen ←'},
'أهلاً بالجميع':{en:'Welcome Everyone',no:'Velkommen alle sammen'},
'لا توجد أخبار':{en:'No news',no:'Ingen nyheter'},
'لا توجد أخبار حالياً':{en:'No news currently',no:'Ingen nyheter for øyeblikket'},
'إضافة خبر جديد':{en:'Add New Article',no:'Legg til ny artikkel'},
'العنوان':{en:'Title',no:'Tittel'},
'المحتوى':{en:'Content',no:'Innhold'},
'صور الخبر':{en:'Article Photos',no:'Artikkelbilder'},
'نشر':{en:'Publish',no:'Publiser'},
'المحاسبة المالية':{en:'Financial Accounting',no:'Finansregnskap'},
'الرصيد':{en:'Balance',no:'Saldo'},
'الإيرادات':{en:'Revenue',no:'Inntekter'},
'المصروفات':{en:'Expenses',no:'Utgifter'},
'المعاملات':{en:'Transactions',no:'Transaksjoner'},
'إضافة معاملة جديدة':{en:'Add New Transaction',no:'Legg til ny transaksjon'},
'إيراد':{en:'Income',no:'Inntekt'},
'مصروف':{en:'Expense',no:'Utgift'},
'الوصف':{en:'Description',no:'Beskrivelse'},
'المبلغ (NOK)':{en:'Amount (NOK)',no:'Beløp (NOK)'},
'التاريخ':{en:'Date',no:'Dato'},
'صور الفواتير':{en:'Invoice Photos',no:'Fakturabilder'},
'حفظ':{en:'Save',no:'Lagre'},
'لا توجد معاملات':{en:'No transactions',no:'Ingen transaksjoner'},
'إجمالي الإيرادات':{en:'Total Revenue',no:'Totale inntekter'},
'إجمالي المصروفات':{en:'Total Expenses',no:'Totale utgifter'},
'الرصيد الحالي':{en:'Current Balance',no:'Nåværende saldo'},
'عدد المعاملات':{en:'Transactions Count',no:'Antall transaksjoner'},
'كل الفترات':{en:'All Periods',no:'Alle perioder'},
'هذا الشهر':{en:'This Month',no:'Denne måneden'},
'آخر 3 أشهر':{en:'Last 3 Months',no:'Siste 3 måneder'},
'هذه السنة':{en:'This Year',no:'I år'},
'النظام الداخلي للجالية الفلسطينية':{en:'Bylaws of the Palestinian Community',no:'Vedtekter for det palestinske samfunnet'},
'تعديل النظام':{en:'Edit Bylaws',no:'Rediger vedtekter'},
'الأهداف':{en:'Goals',no:'Mål'},
'العضوية':{en:'Membership',no:'Medlemskap'},
'الهيئة الإدارية':{en:'Administrative Board',no:'Administrasjonsstyret'},
'الانتخابات':{en:'Elections',no:'Valg'},
'المؤتمرات':{en:'Conferences',no:'Konferanser'},
'المالية':{en:'Finance',no:'Økonomi'},
'المدرسة':{en:'School',no:'Skole'},
'العقوبات':{en:'Penalties',no:'Straffer'},
'للجالية الفلسطينية':{en:'of the Palestinian Community',no:'for det palestinske samfunnet'},
'في روغالاند':{en:'in Rogaland',no:'i Rogaland'},
'إدارة النظام الداخلي':{en:'Manage Bylaws',no:'Administrer vedtekter'},
'اختر الباب':{en:'Select Chapter',no:'Velg kapittel'},
'اختر الباب...':{en:'Select Chapter...',no:'Velg kapittel...'},
'اختر القسم':{en:'Select Section',no:'Velg seksjon'},
'اختر القسم...':{en:'Select Section...',no:'Velg seksjon...'},
'عنوان القسم':{en:'Section Title',no:'Seksjontittel'},
'النقاط (كل سطر نقطة)':{en:'Points (one per line)',no:'Punkter (ett per linje)'},
'الباب':{en:'Chapter',no:'Kapittel'},
'ترسيخ الهوية الوطنية':{en:'Strengthening National Identity',no:'Styrke nasjonal identitet'},
'تعزيز القيم والمبادئ الوطنية الفلسطينية':{en:'Promoting Palestinian national values',no:'Fremme palestinske nasjonale verdier'},
'الحفاظ على الهوية الفلسطينية في المهجر':{en:'Preserving Palestinian identity in diaspora',no:'Bevare palestinsk identitet i diasporaen'},
'تعزيز الروابط الاجتماعية':{en:'Strengthening Social Bonds',no:'Styrke sosiale bånd'},
'تقوية أواصر المحبة والأخوة والتضامن':{en:'Strengthening bonds of love and solidarity',no:'Styrke bånd av kjærlighet og solidaritet'},
'تعزيز الشعور بالانتماء بين أعضاء الجالية':{en:'Enhancing sense of belonging',no:'Styrke følelsen av tilhørighet'},
'دعم القضية الفلسطينية':{en:'Supporting the Palestinian Cause',no:'Støtte den palestinske saken'},
'تقديم الدعم الكامل لنضال الشعب الفلسطيني':{en:'Full support for Palestinian struggle',no:'Full støtte til palestinsk kamp'},
'بكافة أشكاله المشروعة وفق القوانين النرويجية':{en:'In legitimate forms per Norwegian law',no:'I legitime former iht. norsk lov'},
'التواصل مع المجتمع النرويجي':{en:'Engaging with Norwegian Society',no:'Samarbeid med det norske samfunnet'},
'بناء جسور الصداقة والتعاون':{en:'Building bridges of friendship',no:'Bygge broer av vennskap'},
'تعزيز التفاهم المتبادل مع المؤسسات النرويجية':{en:'Mutual understanding with Norwegian institutions',no:'Gjensidig forståelse med norske institusjoner'},
'فئات العضوية':{en:'Membership Categories',no:'Medlemskategorier'},
'العضو العامل: المسدد لاشتراكاته':{en:'Active member: Paid subscriptions',no:'Aktivt medlem: Betalt kontingent'},
'العضو المراقب: غير المسدد أو من عمره 14-18':{en:'Observer: Unpaid or age 14-18',no:'Observatør: Ubetalt eller alder 14-18'},
'عضو الشرف: من قدم خدمات كبيرة للجالية':{en:'Honorary: Outstanding service',no:'Æresmedlem: Fremragende tjeneste'},
'حقوق الأعضاء':{en:'Members Rights',no:'Medlemmers rettigheter'},
'المشاركة في جميع الفعاليات والأنشطة':{en:'Participation in all events',no:'Deltakelse i alle arrangementer'},
'التعبير عن الرأي ديمقراطياً':{en:'Democratic expression',no:'Demokratisk meningsytring'},
'حق التصويت والترشح (للعضو العامل)':{en:'Right to vote and run (active members)',no:'Stemme- og kandidatrett (aktive)'},
'شروط العضوية':{en:'Membership Requirements',no:'Medlemskrav'},
'تعبئة نموذج طلب التسجيل':{en:'Fill registration form',no:'Fyll ut registreringsskjema'},
'دفع رسوم التسجيل والاشتراك السنوي':{en:'Pay registration and annual fees',no:'Betale registrering og kontingent'},
'إكمال 18 عاماً للترشح أو الانتخاب':{en:'Must be 18 to run or vote',no:'Må være 18 for å stille eller stemme'},
'زوال العضوية':{en:'Loss of Membership',no:'Tap av medlemskap'},
'الإخلال بشروط العضوية':{en:'Violation of terms',no:'Brudd på vilkår'},
'الانتقال خارج نطاق الجالية':{en:'Moving out of area',no:'Flytte ut av området'},
'تقديم طلب انسحاب':{en:'Withdrawal request',no:'Uttredelsesforespørsel'},
'الوفاة':{en:'Death',no:'Død'},
'تكوين الهيئة':{en:'Board Composition',no:'Styrets sammensetning'},
'المناصب':{en:'Positions',no:'Stillinger'},
'الرئيس: يرأس الاجتماعات ويمثل الجالية':{en:'President: Chairs meetings',no:'Leder: Leder møter'},
'نائب الرئيس: ينوب عن الرئيس':{en:'Vice President',no:'Nestleder'},
'أمين السر: المحاضر والوثائق':{en:'Secretary: Minutes and documents',no:'Sekretær: Protokoller'},
'أمين الصندوق: الإشراف المالي':{en:'Treasurer: Financial oversight',no:'Kasserer: Økonomisk tilsyn'},
'مسؤول العلاقات: التنسيق الرسمي':{en:'Relations Officer',no:'Relasjonsansvarlig'},
'مسؤول الشؤون الاجتماعية':{en:'Social Affairs Officer',no:'Sosialansvarlig'},
'مسؤول الشؤون الثقافية':{en:'Cultural Affairs Officer',no:'Kulturansvarlig'},
'سقوط العضوية':{en:'Membership Revocation',no:'Tap av medlemskap'},
'التغيب 3 اجتماعات بدون عذر':{en:'3 unexcused absences',no:'3 ugyldige fravær'},
'السفر أكثر من 3 أشهر':{en:'Travel over 3 months',no:'Reise over 3 måneder'},
'الإساءة لسمعة الجالية':{en:'Damaging reputation',no:'Skade omdømme'},
'إجراء الانتخابات':{en:'Election Process',no:'Valgprosess'},
'الاقتراع السري':{en:'Secret ballot',no:'Hemmelig avstemning'},
'فرز الأصوات علناً أمام الجميع':{en:'Public vote counting',no:'Offentlig stemmetelling'},
'الفائزون بأعلى الأصوات':{en:'Winners by highest votes',no:'Vinnere med flest stemmer'},
'شروط الترشح':{en:'Candidacy Requirements',no:'Kandidaturkrav'},
'مرور 6 شهور من تاريخ التسجيل':{en:'6 months since registration',no:'6 måneder siden registrering'},
'إتمام 18 عاماً يوم الانتخاب':{en:'Must be 18 on election day',no:'Må være 18 på valgdagen'},
'تسديد الاشتراكات':{en:'Paid subscriptions',no:'Betalt kontingent'},
'إقامة قانونية للترشح':{en:'Legal residence to run',no:'Lovlig opphold for å stille'},
'المؤتمر العام':{en:'General Conference',no:'Generalkonferanse'},
'يعقد سنوياً بدعوة من الهيئة الإدارية':{en:'Held annually by board invitation',no:'Holdes årlig etter styrets invitasjon'},
'الإعلان قبل أسبوعين على الأقل':{en:'Announced 2 weeks prior',no:'Kunngjort 2 uker i forveien'},
'النصاب: ثلثي الأعضاء العاملين':{en:'Quorum: Two-thirds of active members',no:'Beslutningsdyktighet: To tredjedeler'},
'الجمعية العمومية':{en:'General Assembly',no:'Generalforsamling'},
'تنعقد مرة كل 6 شهور على الأقل':{en:'Held at least every 6 months',no:'Holdes minst hver 6. måned'},
'النصاب: النصف زائد واحد':{en:'Quorum: Half plus one',no:'Halvparten pluss én'},
'الهيئة العليا للجالية عند انعقادها':{en:'Highest authority when in session',no:'Høyeste myndighet'},
'القرارات':{en:'Decisions',no:'Beslutninger'},
'الأغلبية النسبية للتصويت العادي':{en:'Simple majority for regular votes',no:'Simpelt flertall'},
'ثلثي الأعضاء لتعديل النظام الداخلي':{en:'Two-thirds to amend bylaws',no:'To tredjedeler for å endre vedtekter'},
'الميزانية':{en:'Budget',no:'Budsjett'},
'رسوم الانتساب والاشتراك السنوي':{en:'Registration and annual fees',no:'Registrering og kontingent'},
'المساعدات والتبرعات غير المشروطة':{en:'Unconditional donations',no:'Ubetingede donasjoner'},
'دخل النشاطات والفعاليات':{en:'Income from activities',no:'Inntekter fra aktiviteter'},
'إدارة الأموال':{en:'Financial Management',no:'Økonomistyring'},
'تودع في البنك باسم الجالية':{en:'Deposited in community account',no:'Innsatt på samfunnets konto'},
'الرئيس وأمين الصندوق مسؤولان':{en:'President and treasurer responsible',no:'Leder og kasserer ansvarlige'},
'نظام محاسبي وفق القوانين النرويجية':{en:'Accounting per Norwegian law',no:'Regnskap iht. norsk lov'},
'الرقابة':{en:'Oversight',no:'Tilsyn'},
'مدقق حسابات قانوني معتمد':{en:'Certified auditor',no:'Sertifisert revisor'},
'تقارير مالية دورية':{en:'Periodic financial reports',no:'Periodiske finansrapporter'},
'الشفافية والمصداقية':{en:'Transparency and credibility',no:'Åpenhet og troverdighet'},
'تعليم اللغة العربية':{en:'Teaching Arabic',no:'Undervisning i arabisk'},
'الحفاظ على التراث الفلسطيني':{en:'Preserving Palestinian heritage',no:'Bevare palestinsk kulturarv'},
'تعزيز الهوية الوطنية':{en:'Strengthening national identity',no:'Styrke nasjonal identitet'},
'الإدارة':{en:'Management',no:'Ledelse'},
'مجلس إدارة من الهيئة الإدارية':{en:'Board from admin body',no:'Styre fra administrasjonen'},
'مدير معين من الهيئة':{en:'Director appointed by board',no:'Direktør utnevnt av styret'},
'ممثل عن أولياء الأمور':{en:'Parent representative',no:'Foreldrerepresentant'},
'الأنشطة':{en:'Activities',no:'Aktiviteter'},
'فرقة دبكة فلسطينية':{en:'Palestinian dabke troupe',no:'Palestinsk dabke-gruppe'},
'فعاليات تراثية وثقافية':{en:'Cultural heritage events',no:'Kulturarvsarrangementer'},
'التوعية الوطنية':{en:'National awareness',no:'Nasjonal bevissthet'},
'أنواع العقوبات':{en:'Types of Penalties',no:'Typer straffer'},
'التنبيه':{en:'Warning',no:'Advarsel'},
'اللوم':{en:'Reprimand',no:'Irettesettelse'},
'الإنذار':{en:'Final Warning',no:'Siste advarsel'},
'تجميد العضوية':{en:'Membership freeze',no:'Frysing av medlemskap'},
'الفصل من العضوية':{en:'Expulsion',no:'Utvisning'},
'الضوابط':{en:'Procedures',no:'Prosedyrer'},
'البحث والتحقق من الخلل':{en:'Investigation',no:'Undersøkelse'},
'دعوة العضو للمراجعة':{en:'Invite member for review',no:'Invitere til gjennomgang'},
'النقاش في اجتماع مغلق':{en:'Closed meeting discussion',no:'Diskusjon i lukket møte'},
'إبلاغ العضو بالقرار خطياً':{en:'Written notification',no:'Skriftlig melding'},
'الباب الثاني - المادة 9':{en:'Chapter 2 - Article 9',no:'Kapittel 2 - Artikkel 9'},
'الباب الثالث - المواد 10-16':{en:'Chapter 3 - Articles 10-16',no:'Kapittel 3 - Artikler 10-16'},
'الباب السادس - المواد 36-47':{en:'Chapter 6 - Articles 36-47',no:'Kapittel 6 - Artikler 36-47'},
'الباب الرابع - المواد 17-20':{en:'Chapter 4 - Articles 17-20',no:'Kapittel 4 - Artikler 17-20'},
'الباب الخامس - المواد 21-35':{en:'Chapter 5 - Articles 21-35',no:'Kapittel 5 - Artikler 21-35'},
'الباب السابع':{en:'Chapter 7',no:'Kapittel 7'},
'المدرسة العربية':{en:'Arabic School',no:'Arabisk skole'},
'الباب الثامن':{en:'Chapter 8',no:'Kapittel 8'},
'1-50 عضو ← 5 أعضاء هيئة':{en:'1-50 → 5 board members',no:'1-50 → 5 styremedlemmer'},
'51-150 عضو ← 7 أعضاء':{en:'51-150 → 7 members',no:'51-150 → 7 medlemmer'},
'151-250 عضو ← 9 أعضاء':{en:'151-250 → 9 members',no:'151-250 → 9 medlemmer'},
'أكثر من 250 ← 11 عضو':{en:'Over 250 → 11 members',no:'Over 250 → 11 medlemmer'},
'شارك برأيك في قرارات الجالية':{en:'Share your opinion on community decisions',no:'Del din mening om fellesskapets beslutninger'},
'لا توجد تصويتات نشطة حالياً':{en:'No active votes currently',no:'Ingen aktive avstemninger'},
'إنشاء وإدارة التصويتات':{en:'Create and manage votes',no:'Opprett og administrer avstemninger'},
'إنشاء تصويت جديد':{en:'Create New Vote',no:'Opprett ny avstemning'},
'عنوان التصويت':{en:'Vote Title',no:'Avstemningstitel'},
'السؤال / الوصف':{en:'Question / Description',no:'Spørsmål / Beskrivelse'},
'نوع التصويت':{en:'Vote Type',no:'Avstemningstype'},
'موافق / غير موافق':{en:'Agree / Disagree',no:'Enig / Uenig'},
'خيارات متعددة (انتخابات)':{en:'Multiple Choice',no:'Flervalg'},
'المرشحين / الخيارات (كل سطر = خيار)':{en:'Candidates (one per line)',no:'Kandidater (ett per linje)'},
'كم صوت مسموح لكل عضو؟':{en:'Votes per member?',no:'Stemmer per medlem?'},
'إنشاء التصويت':{en:'Create Vote',no:'Opprett avstemning'},
'التصويتات الحالية':{en:'Current Votes',no:'Gjeldende avstemninger'},
'لا توجد تصويتات':{en:'No votes',no:'Ingen avstemninger'},
'مفتوح':{en:'Open',no:'Åpen'},
'مغلق':{en:'Closed',no:'Lukket'},
'موافق':{en:'Agree',no:'Enig'},
'غير موافق':{en:'Disagree',no:'Uenig'},
'صوتوا':{en:'Voted',no:'Stemt'},
'لم يصوت أحد بعد':{en:'No one voted yet',no:'Ingen har stemt ennå'},
'إجمالي الأصوات':{en:'Total Votes',no:'Totalt stemmer'},
'الكل':{en:'All',no:'Alle'},
'موقعي':{en:'My Location',no:'Min posisjon'},
'أفضل موقع للاجتماع':{en:'Best Meeting Point',no:'Beste møtested'},
'على الخريطة':{en:'On Map',no:'På kartet'},
'مخفي':{en:'Hidden',no:'Skjult'},
'مدينة':{en:'City',no:'By'},
'إحصائيات':{en:'Statistics',no:'Statistikk'},
'مدن مختلفة':{en:'Different Cities',no:'Forskjellige byer'},
'انضم إلى الجالية الفلسطينية في روغالاند':{en:'Join the Palestinian Community in Rogaland',no:'Bli med i det palestinske samfunnet i Rogaland'},
'المعلومات الشخصية':{en:'Personal Information',no:'Personlig informasjon'},
'الاسم الكامل':{en:'Full Name',no:'Fullt navn'},
'رقم الهاتف':{en:'Phone Number',no:'Telefonnummer'},
'البريد الإلكتروني':{en:'Email',no:'E-post'},
'معلومات السكن':{en:'Residence Info',no:'Bostedinformasjon'},
'المدينة / المنطقة':{en:'City / Area',no:'By / Område'},
'العنوان الكامل':{en:'Full Address',no:'Full adresse'},
'اختياري':{en:'Optional',no:'Valgfritt'},
'بحث':{en:'Search',no:'Søk'},
'موقعي الحالي':{en:'My Location',no:'Nåværende posisjon'},
'الأصل الفلسطيني':{en:'Palestinian Origin',no:'Palestinsk opprinnelse'},
'البلد الأصلي في فلسطين':{en:'Original City in Palestine',no:'Opprinnelig by i Palestina'},
'أفراد العائلة':{en:'Family Members',no:'Familiemedlemmer'},
'عدد أفراد الأسرة (بما فيهم أنت)':{en:'Family size (including you)',no:'Familiestørrelse (inkludert deg)'},
'إضافة فرد من العائلة':{en:'Add Family Member',no:'Legg til familiemedlem'},
'ملاحظات إضافية':{en:'Additional Notes',no:'Tilleggsinformasjon'},
'هل لديك أي ملاحظات أو اقتراحات؟':{en:'Any notes or suggestions?',no:'Notater eller forslag?'},
'إعدادات الخصوصية':{en:'Privacy Settings',no:'Personverninnstillinger'},
'إظهار موقعي على الخريطة':{en:'Show my location on map',no:'Vis min posisjon på kartet'},
'إظهار رقم هاتفي للأعضاء':{en:'Show phone to members',no:'Vis telefon til medlemmer'},
'إظهار بريدي الإلكتروني للأعضاء':{en:'Show email to members',no:'Vis e-post til medlemmer'},
'أوافق على الانضمام للجالية الفلسطينية والالتزام بأهدافها':{en:'I agree to join and commit to its goals',no:'Jeg samtykker å bli med og forplikte meg'},
'إرسال طلب الانتساب':{en:'Submit Registration',no:'Send registrering'},
'تم إرسال طلبك بنجاح!':{en:'Request sent successfully!',no:'Forespørsel sendt!'},
'شكراً لانضمامك للملتقى الفلسطيني في روغالاند':{en:'Thank you for joining!',no:'Takk for at du ble med!'},
'سيتم مراجعة طلبك والتواصل معك قريباً':{en:'We will review and contact you soon',no:'Vi gjennomgår og kontakter deg snart'},
'تقديم طلب آخر':{en:'Submit Another',no:'Send en annen'},
'العودة للرئيسية':{en:'Back to Home',no:'Tilbake til hjem'},
'زوج/زوجة':{en:'Spouse',no:'Ektefelle'},
'ابن':{en:'Son',no:'Sønn'},
'ابنة':{en:'Daughter',no:'Datter'},
'أب':{en:'Father',no:'Far'},
'أم':{en:'Mother',no:'Mor'},
'أخ':{en:'Brother',no:'Bror'},
'أخت':{en:'Sister',no:'Søster'},
'أرسل لنا رسالتك أو اقتراحك':{en:'Send us your message',no:'Send oss din melding'},
'اسمك':{en:'Your Name',no:'Ditt navn'},
'الموضوع':{en:'Subject',no:'Emne'},
'الرسالة':{en:'Message',no:'Melding'},
'إرسال الرسالة':{en:'Send Message',no:'Send melding'},
'تم إرسال رسالتك بنجاح!':{en:'Message sent!',no:'Melding sendt!'},
'شكراً لتواصلك معنا. سنرد عليك في أقرب وقت.':{en:'Thank you. We will reply soon.',no:'Takk. Vi svarer snart.'},
'إرسال رسالة أخرى':{en:'Send Another',no:'Send en annen'},
'صندوق الرسائل':{en:'Inbox',no:'Innboks'},
'إدارة رسائل الزوار والأعضاء':{en:'Manage messages',no:'Administrer meldinger'},
'إجمالي الرسائل':{en:'Total Messages',no:'Totalt meldinger'},
'غير مقروءة':{en:'Unread',no:'Uleste'},
'مقروءة':{en:'Read',no:'Leste'},
'تفاصيل الرسالة':{en:'Message Details',no:'Meldingsdetaljer'},
'لا توجد رسائل':{en:'No messages',no:'Ingen meldinger'},
'اقتراح':{en:'Suggestion',no:'Forslag'},
'استفسار':{en:'Inquiry',no:'Forespørsel'},
'شكوى':{en:'Complaint',no:'Klage'},
'طلب مساعدة':{en:'Help Request',no:'Hjelpeforespørsel'},
'تطوع':{en:'Volunteer',no:'Frivillig'},
'أخرى':{en:'Other',no:'Annet'},
'شاهد الفعاليات مباشرة وشارك بالتصويت':{en:'Watch live and vote',no:'Se direkte og stem'},
'مباشر الآن':{en:'Live Now',no:'Direkte nå'},
'لا يوجد بث مباشر حالياً':{en:'No live stream',no:'Ingen direktesending'},
'تابعنا للإعلان عن البث القادم':{en:'Follow for upcoming broadcasts',no:'Følg for kommende sendinger'},
'صوّت الآن':{en:'Vote Now',no:'Stem nå'},
'شارك بصوتك أثناء مشاهدة البث':{en:'Vote while watching',no:'Stem mens du ser på'},
'إعداد وتشغيل البث المباشر':{en:'Setup live stream',no:'Sett opp direktesending'},
'إعدادات البث':{en:'Stream Settings',no:'Sendeinnstillinger'},
'عنوان البث':{en:'Stream Title',no:'Sendetittel'},
'رابط البث (YouTube أو Facebook Live)':{en:'Stream URL (YouTube or Facebook)',no:'Sendelenke (YouTube eller Facebook)'},
'ربط تصويت بالبث (اختياري)':{en:'Link vote to stream (optional)',no:'Koble avstemning (valgfritt)'},
'بدء البث':{en:'Start Stream',no:'Start sending'},
'إيقاف البث':{en:'Stop Stream',no:'Stopp sending'},
'البث متوقف':{en:'Stream stopped',no:'Sending stoppet'},
'دليل البث المباشر':{en:'Stream Guide',no:'Sendingsguide'},
'معاينة':{en:'Preview',no:'Forhåndsvisning'},
'تقارير شاملة جاهزة للطباعة والتصدير':{en:'Reports ready for print',no:'Rapporter klare for utskrift'},
'إجمالي الأعضاء':{en:'Total Members',no:'Totalt medlemmer'},
'العائلات المسجلة':{en:'Registered Families',no:'Registrerte familier'},
'إجمالي التصويتات':{en:'Total Votes',no:'Totalt avstemninger'},
'نشطة حالياً':{en:'Active Now',no:'Aktive nå'},
'مغلقة':{en:'Closed',no:'Lukket'},
'متوسط المشاركة':{en:'Avg. Participation',no:'Gj.snitt deltakelse'},
'أعضاء جدد (هذا الشهر)':{en:'New Members (this month)',no:'Nye medlemmer (denne måneden)'},
'تقرير':{en:'Report',no:'Rapport'},
'صور الفعاليات والمناسبات':{en:'Events Photos',no:'Bilder fra arrangementer'},
'إضافة ألبوم جديد':{en:'Add Album',no:'Legg til album'},
'اسم الألبوم':{en:'Album Name',no:'Albumnavn'},
'الصور':{en:'Photos',no:'Bilder'},
'لا توجد ألبومات بعد':{en:'No albums yet',no:'Ingen album ennå'},
'لا توجد ألبومات':{en:'No albums',no:'Ingen album'},
'الاسم بالعربي':{en:'Name in Arabic',no:'Navn på arabisk'},
'الاسم بالإنجليزي/النرويجي':{en:'Name in English/Norwegian',no:'Navn på engelsk/norsk'},
'اسم الجالية (عربي)':{en:'Name (Arabic)',no:'Navn (arabisk)'},
'اسم الجالية (إنجليزي)':{en:'Name (English)',no:'Navn (engelsk)'},
'احفظ نسخة من كل بياناتك أو استعدها في أي وقت':{en:'Backup or restore anytime',no:'Sikkerhetskopier når som helst'},
'تخصيص الصفحة الرئيسية':{en:'Customize Home Page',no:'Tilpass hjemmesiden'},
'اختر العناصر التي تريد عرضها في الصفحة الرئيسية وخصص محتواها':{en:'Choose elements to display',no:'Velg elementer som skal vises'},
'العنوان الرئيسي':{en:'Main Title',no:'Hovedtittel'},
'العنوان الفرعي':{en:'Subtitle',no:'Undertittel'},
'النص الفرعي':{en:'Subtitle',no:'Undertittel'},
'نص الزر الأول':{en:'Button 1 Text',no:'Knapp 1 tekst'},
'نص الزر الثاني':{en:'Button 2 Text',no:'Knapp 2 tekst'},
'الإحصائيات':{en:'Statistics',no:'Statistikk'},
'عدد الأخبار المعروضة':{en:'News count shown',no:'Antall nyheter vist'},
'نبذة عن الجالية':{en:'About Us',no:'Om oss'},
'الرؤية':{en:'Vision',no:'Visjon'},
'واتساب (رقم المجموعة)':{en:'WhatsApp (group)',no:'WhatsApp (gruppe)'},
'للجميع':{en:'Public',no:'Offentlig'},
'للمسؤول فقط':{en:'Admin Only',no:'Kun admin'},
'قائمة الأعضاء':{en:'Members List',no:'Medlemsliste'},
'اسم المستخدم':{en:'Username',no:'Brukernavn'},
'كلمة المرور':{en:'Password',no:'Passord'},
'النسخ الاحتياطي':{en:'Backup',no:'Sikkerhetskopi'},
'التوقيع':{en:'Signature',no:'Signatur'},
'سياسة الخصوصية':{en:'Privacy Policy',no:'Personvernerklæring'},
'حق الوصول:':{en:'Right of Access:',no:'Innsynsrett:'},
'حق التصحيح:':{en:'Right to Rectification:',no:'Rett til retting:'},
'حق الحذف:':{en:'Right to Erasure:',no:'Rett til sletting:'},
'حق سحب الموافقة:':{en:'Withdraw Consent:',no:'Trekke samtykke:'},
'حق تقديم شكوى:':{en:'Right to Complain:',no:'Rett til å klage:'},
'البيانات محفوظة بشكل مشفّر ومحمي':{en:'Data is encrypted and protected',no:'Data er kryptert og beskyttet'},
'الوصول للبيانات مقتصر على المسؤولين المعتمدين فقط':{en:'Access limited to authorized admins',no:'Tilgang begrenset til autoriserte'},
'لا نبيع أو نتاجر بالبيانات الشخصية أبداً':{en:'We never sell personal data',no:'Vi selger aldri personopplysninger'},
'لا نشارك بياناتكم مع أي طرف ثالث بدون إذنكم':{en:'No sharing without consent',no:'Ingen deling uten samtykke'},
'بيانات الأعضاء':{en:'Members Data',no:'Medlemsdata'},
'بيانات الزوار':{en:'Visitor Data',no:'Besøksdata'},
'بيانات تقنية':{en:'Technical Data',no:'Tekniske data'},
'تأكيد':{en:'Confirm',no:'Bekreft'},
'إلغاء':{en:'Cancel',no:'Avbryt'},
'إغلاق':{en:'Close',no:'Lukk'},
'تعديل':{en:'Edit',no:'Rediger'},
'حذف':{en:'Delete',no:'Slett'},
'إضافة':{en:'Add',no:'Legg til'},
'نعم':{en:'Yes',no:'Ja'},
'لا':{en:'No',no:'Nei'},
'معلق':{en:'Pending',no:'Venter'},
'مقبول':{en:'Accepted',no:'Godkjent'},
'مرفوض':{en:'Rejected',no:'Avvist'},
'قبول':{en:'Accept',no:'Godta'},
'رفض':{en:'Reject',no:'Avvis'},
'مطلوب':{en:'Required',no:'Påkrevd'},
'ملاحظات':{en:'Notes',no:'Notater'},
'هل تريد حذف؟':{en:'Delete?',no:'Slette?'},
'دخول':{en:'Login',no:'Logg inn'},
'لا توجد بيانات':{en:'No data',no:'Ingen data'},
'طلب معلق':{en:'Pending Request',no:'Ventende forespørsel'},
'عائلة مقبولة':{en:'Approved Family',no:'Godkjent familie'},
'مراجعة وإدارة طلبات الانتساب':{en:'Review requests',no:'Gjennomgå forespørsler'},
'الاسم':{en:'Name',no:'Navn'},
'الاسم *':{en:'Name *',no:'Navn *'},
'الاسم الأول':{en:'First Name',no:'Fornavn'},
'اسم العائلة':{en:'Last Name',no:'Etternavn'},
'الهاتف':{en:'Phone',no:'Telefon'},
'المدينة':{en:'City',no:'By'},
'عدد أفراد العائلة':{en:'Family Size',no:'Familiestørrelse'},
'الرسوم (NOK)':{en:'Fees (NOK)',no:'Avgift (NOK)'},
'الدفع':{en:'Payment',no:'Betaling'},
'فواتير':{en:'Invoices',no:'Fakturaer'},
'النوع':{en:'Type',no:'Type'},
'المبلغ':{en:'Amount',no:'Beløp'},
'تاريخ التسجيل':{en:'Registration Date',no:'Registreringsdato'},
'من':{en:'From',no:'Fra'},
'إلى':{en:'To',no:'Til'},
'لا يوجد أعضاء':{en:'No members',no:'Ingen medlemmer'},
'لا يوجد أرشيف':{en:'No archive',no:'Ingen arkiv'},
'صورة العضو':{en:'Member Photo',no:'Medlemsbilde'},
'الحالة':{en:'Status',no:'Status'},
'المكان':{en:'Location',no:'Sted'},
'وقت البدء':{en:'Start Time',no:'Starttid'},
'الترحيب':{en:'Welcome',no:'Velkomst'},
'نص الختام':{en:'Closing Text',no:'Avslutningstekst'},
'نص الدعوة':{en:'Invitation Text',no:'Invitasjonstekst'},
'عنوان المؤتمر':{en:'Conference Title',no:'Konferansetittel'},
'الآية':{en:'Verse',no:'Vers'},
'المرجع':{en:'Reference',no:'Referanse'},
'يسرنا دعوتكم':{en:'We invite you',no:'Vi inviterer deg'},
'الموافقة':{en:'Consent',no:'Samtykke'},
'الجالية الفلسطينية في روغالاند':{en:'Palestinian Community in Rogaland',no:'Det palestinske samfunnet i Rogaland'},
'فلسطين':{en:'Palestine',no:'Palestina'},
'مهم:':{en:'Important:',no:'Viktig:'},
'صور':{en:'Photos',no:'Bilder'},
'تسجيل جميع أعضاء الجالية الفلسطينية':{en:'Register all members',no:'Registrer alle medlemmer'},
'لا توجد نتائج للبحث':{en:'No results',no:'Ingen resultater'},
'السماح لجميع الزوار بمشاهدة البث (بدون الحاجة لتسجيل الدخول)':{en:'Allow all visitors to watch',no:'Tillat alle å se'},
'انسخ رابط البث والصقه هنا':{en:'Paste stream link here',no:'Lim inn sendelenke her'},
'أنشئ دعوة احترافية بتصميم فلسطيني':{en:'Create professional invitation',no:'Lag profesjonell invitasjon'},
'إظهار البريد':{en:'Show Email',no:'Vis e-post'},
'إظهار الهاتف':{en:'Show Phone',no:'Vis telefon'},
'إظهار على الخريطة':{en:'Show on Map',no:'Vis på kartet'},
'رب الأسرة':{en:'Head of Family',no:'Familieoverhode'},
'عدد الصفوف':{en:'Rows',no:'Rader'},
'الرمز':{en:'Code',no:'Kode'},
'العضو':{en:'Member',no:'Medlem'},
'السنة':{en:'Year',no:'År'},
'النص':{en:'Text',no:'Tekst'},
'الأعضاء':{en:'Members',no:'Medlemmer'},
'العائلات':{en:'Families',no:'Familier'},
'دفعوا':{en:'Paid',no:'Betalt'},
'لم يدفعوا':{en:'Unpaid',no:'Ikke betalt'},
'المحصّل':{en:'Collected',no:'Innsamlet'},
'الخريطة':{en:'Map',no:'Kart'},
'التقارير':{en:'Reports',no:'Rapporter'},
'تفاصيل الطلب':{en:'Request Details',no:'Forespørseldetaljer'},
'تعديل بيانات العائلة':{en:'Edit Family Data',no:'Rediger familiedata'},
'انتخاب رئيس اللجنة':{en:'Committee Chair Election',no:'Valg av komitéleder'},
'لا توجد طلبات معلقة':{en:'No pending requests',no:'Ingen ventende forespørsler'},
'الطلبات المعلقة':{en:'Pending Requests',no:'Ventende forespørsler'},
'العائلات المقبولة':{en:'Approved Families',no:'Godkjente familier'},
'لا توجد عائلات مقبولة بعد':{en:'No approved families yet',no:'Ingen godkjente familier ennå'},
'تغيير رموز التصويت':{en:'Change Vote Codes',no:'Endre stemmekoder'},
};

// Sort keys longest-first for partial matching
var sortedKeys = Object.keys(dict).sort(function(a,b){return b.length-a.length;});

function translateTextNode(node, lang){
  if(!node._origText) node._origText = node.textContent;
  if(lang==='ar'){node.textContent=node._origText;return;}
  var orig = node._origText;
  var trimmed = orig.trim();
  if(!trimmed) return;
  // Direct match
  if(dict[trimmed]&&dict[trimmed][lang]){
    node.textContent = orig.replace(trimmed, dict[trimmed][lang]);
    return;
  }
  // Partial replacement
  var text = orig;
  var changed = false;
  for(var i=0;i<sortedKeys.length;i++){
    var k=sortedKeys[i];
    if(k.length<2) continue;
    if(text.indexOf(k)!==-1 && dict[k][lang]){
      text = text.split(k).join(dict[k][lang]);
      changed = true;
    }
  }
  if(changed) node.textContent = text;
}

function walkDOM(node, lang){
  if(!node) return;
  if(node.nodeType===3){translateTextNode(node,lang);return;}
  if(node.nodeType!==1) return;
  var tag=node.tagName;
  if(tag==='SCRIPT'||tag==='STYLE'||tag==='TEXTAREA') return;
  // Placeholder
  if(node.placeholder){
    if(!node._origPH) node._origPH=node.placeholder;
    if(lang==='ar'){node.placeholder=node._origPH;}
    else{var ph=node._origPH.trim();if(dict[ph]&&dict[ph][lang])node.placeholder=dict[ph][lang];}
  }
  // Options
  if(tag==='OPTION'){
    if(!node._origOT) node._origOT=node.textContent;
    if(lang==='ar'){node.textContent=node._origOT;}
    else{var ot=node._origOT.trim();if(dict[ot]&&dict[ot][lang])node.textContent=dict[ot][lang];}
    return;
  }
  for(var i=0;i<node.childNodes.length;i++) walkDOM(node.childNodes[i],lang);
}

function fullTranslate(lang){walkDOM(document.body,lang);}

// Override setLanguage safely
var _orig = window.setLanguage;
window.setLanguage = function(lang){
  if(_orig) _orig(lang);
  setTimeout(function(){
    fullTranslate(lang);
    setTimeout(function(){fullTranslate(lang);},800);
  },300);
};

// MutationObserver for dynamic content
var curLang = localStorage.getItem('appLang')||'ar';
if(curLang!=='ar'){
  var mo = new MutationObserver(function(muts){
    var l=localStorage.getItem('appLang')||'ar';
    if(l==='ar') return;
    for(var i=0;i<muts.length;i++){
      var added=muts[i].addedNodes;
      for(var j=0;j<added.length;j++) walkDOM(added[j],l);
    }
  });
  mo.observe(document.body,{childList:true,subtree:true});
}

// Initial translation
var initLang = localStorage.getItem('appLang')||'ar';
if(initLang!=='ar'){
  var run=function(){setTimeout(function(){fullTranslate(initLang);},500);};
  if(document.readyState==='complete') run();
  else window.addEventListener('load',run);
}

console.log('🌍 translate.js: '+Object.keys(dict).length+' phrases loaded');
})();
